version: "3.8"

configs:
  collector_config: 
    file: ./collector.yaml

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    depends_on:
      - rabbitmq

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    depends_on:
      - rabbitmq
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my-database
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.66.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    configs:
      - source: collector_config
        target: /etc/otel-collector-config.yaml

volumes:
  db:
    driver: local